require.config({
    baseUrl:'https://img1.tiancitycdn.com/cls/homepage/v1/js/requirePbl/',
    paths: {
        jquery: 'lib/jquery-1.7.2.min',
        barryFall: 'api/barryFall',
        popView: 'api/popView',
        preview:'api/preview',
        loadImg:'api/loadImg'
    }
});
 
require(['jquery','barryFall','popView','preview','loadImg'], function($,barryFall,popView,preview,loadImg) {
    $(function(){
        var options = {
            'picPath':'https://img1.tiancitycdn.com/cls/homepage/v1/images/pic/fan/',
            'minpicPath':'https://img1.tiancitycdn.com/cls/homepage/v1/images/minpic/fan/',
            'unitData':[
                {'img':'fan47.jpg',
                 'width':'1000',
                 'height':'1812',
                 'intro':'作品名：清新梦<br>作者名：swd3e2'
                },
                {'img':'fan48.jpg',
                 'width':'1000',
                 'height':'1250',
                 'intro':'作品名：混搭大法好<br>作者名：swd3e2'
                },
                {'img':'fan49.jpg',
                 'width':'1000',
                 'height':'1539',
                 'intro':'作品名：蕾比雅黑暗光辉<br>作者名：swd3e2'
                },
                {'img':'fan50.jpg',
                 'width':'1000',
                 'height':'1414',
                 'intro':'作品名：缇娜<br>作者名：吃撑猫'
                },
                {'img':'fan51.jpg',
                 'width':'1000',
                 'height':'1318',
                 'intro':'作品名：暗夜洛丽塔<br>作者名：伶乃'
                },
                {'img':'fan52.jpg',
                 'width':'1000',
                 'height':'1381',
                 'intro':'作品名：缇娜泳装<br>作者名：伶乃'
                },
                {'img':'fan53.jpg',
                 'width':'1000',
                 'height':'1710',
                 'intro':'作品名：蕾比亚天空<br>作者名：紫咲さとり'
                },
                {'img':'fan54.jpg',
                 'width':'1000',
                 'height':'1368',
                 'intro':'作品名：蕾比雅泳装<br>作者名：紫咲さとり'
                },
                {'img':'fan55.jpg',
                 'width':'1000',
                 'height':'1428',
                 'intro':'作品名：缇娜<br>作者名：CodeAign'
                },
                {'img':'fan56.jpg',
                 'width':'1000',
                 'height':'561',
                 'intro':'作品名：牙白<br>作者名：木户蕾'
                },
                {'img':'fan57.jpg',
                 'width':'1000',
                 'height':'1376',
                 'intro':'作品名：李瑟钰<br>作者名：FREE_WIND_YO0'
                },
                {'img':'fan58.jpg',
                 'width':'1000',
                 'height':'1414',
                 'intro':'作品名：蕾比雅兔女郎<br>作者名：岚'
                },
                {'img':'fan59.jpg',
                 'width':'1000',
                 'height':'701',
                 'intro':'作品名：二转尤莉<br>作者名：小黑 快跑！'
                },
                {'img':'fan30.jpg',
                 'width':'690',
                 'height':'976',
                 'intro':'作品名：兵器少女！缇娜！<br>作者名：蛆虫音'
                },
                /*{'img':'fan27.jpg',
                 'width':'662',
                 'height':'1200',
                 'intro':'作品名：LucidDream<br>作者名：swd3e2'
                },*/
                {'img':'fan24.jpg',
                 'width':'750',
                 'height':'1136',
                 'intro':'作品名：3+3=6<br>作者名：伶乃'
                },
                {'img':'fan19.jpg',
                 'width':'450',
                 'height':'636',
                 'intro':'作品名：幼粉毛<br>作者名：伶乃'
                }, 
                {'img':'fan13.jpg',
                 'width':'450',
                 'height':'637',
                 'intro':'作品名：J叔同人作品<br>作者名：★苍狼野兽★'
                },
                {'img':'fan43.jpg',
                 'width':'542',
                 'height':'930',
                 'intro':'作品名：勇者最喜欢巨乳啦~<br>作者名：天上天下老司机'
                },
                {'img':'fan14.jpg',
                 'width':'707',
                 'height':'1000',
                 'intro':'作品名：小米吃棒棒糖<br>作者名：怀念吹过的风'
                },
                {'img':'fan0.jpg',
                 'width':'1000',
                 'height':'1414',
                 'intro':'作品名：兔女郎瑟钰<br>作者名：路过滴天天'
                },
                {'img':'fan25.jpg',
                 'width':'700',
                 'height':'825',
                 'intro':'作品名：7把铲子<br>作者名：三色猫'
                },
                {'img':'fan15.jpg',
                 'width':'621',
                 'height':'881',
                 'intro':'作品名：尤莉出浴图<br>作者名：萌尽'
                },
                {'img':'fan42.jpg',
                 'width':'700',
                 'height':'990',
                 'intro':'作品名：樱花易逝<br>作者名：绫纱岚'
                },
                {'img':'fan33.jpg',
                 'width':'700',
                 'height':'1079',
                 'intro':'作品名：雷比亚应援<br>作者名：三色猫'
                },
                {'img':'fan44.jpg',
                 'width':'2500',
                 'height':'1644',
                 'intro':'作品名：红狼小队缇娜<br>作者名：络樱Sama丶'
                },
                {'img':'fan45.jpg',
                 'width':'2146',
                 'height':'2871',
                 'intro':'作品名：萌萌哒缇娜<br>作者名：yukiusa'
                },
                {'img':'fan46.jpg',
                 'width':'700',
                 'height':'1079',
                 'intro':'作品名：束缚<br>作者名：森林栄二'
                },
                {'img':'fan21.jpg',
                 'width':'690',
                 'height':'940',
                 'intro':'作品名：正太小米出击<br>作者名：時雨時桜de牛奶君'
                },
                {'img':'fan22.jpg',
                 'width':'856',
                 'height':'1110',
                 'intro':'作品名：女仆装小米<br>作者名：時雨時桜de牛奶君'
                },
                /*{'img':'fan32.jpg',
                 'width':'700',
                 'height':'986',
                 'intro':'作品名：蓝毛一脸懵逼<br>作者名：音雨の時雨'
                },
                {'img':'fan31.jpg',
                 'width':'510',
                 'height':'850',
                 'intro':'作品名：和服大姐<br>作者名：咸鱼w'
                },*/
                {'img':'fan35.jpg',
                 'width':'700',
                 'height':'990',
                 'intro':'作品名：蕾比亚超可爱！<br>作者名：紫咲satori'
                },
                {'img':'fan34.jpg',
                 'width':'800',
                 'height':'496',
                 'intro':'作品名：蕾比雅大法好<br>作者名：吃撑喵'
                },
                {'img':'fan12.jpg',
                 'width':'1000',
                 'height':'707',
                 'intro':'作品名：女巫大姐<br>作者名：DM丶CG'
                },
                {'img':'fan11.jpg',
                 'width':'1000',
                 'height':'707',
                 'intro':'作品名：花嫁C酱<br>作者名：『逆廻』十六夜'
               },
                {'img':'fan26.jpg',
                 'width':'700',
                 'height':'467',
                 'intro':'作品名：ClosersTina<br>作者名：木户蕾'
                },
               {'img':'fan8.jpg',
                 'width':'580',
                 'height':'820',
                 'intro':'作品名：比基尼尤莉<br>作者名：volovey'
                },
                {'img':'fan23.jpg',
                 'width':'900',
                 'height':'850',
                 'intro':'作品名：黑羊小队棒棒糖<br>作者名：亚仯'
               },
                {'img':'fan28.jpg',
                 'width':'700',
                 'height':'700',
                 'intro':'作品名：tina的微笑<br>作者名：绿芽子'
              },
                {'img':'fan36.jpg',
                 'width':'700',
                 'height':'700',
                 'intro':'作品名：蕾比亚第夏日祭<br>作者名：绿芽子'
                },
                {'img':'fan37.jpg',
                 'width':'700',
                 'height':'700',
                 'intro':'作品名：魔法少女缇娜<br>作者名：makura'
                },
                {'img':'fan38.jpg',
                 'width':'700',
                 'height':'560',
                 'intro':'作品名：汝不平何以？缇娜！<br>作者名：木户蕾'
                },
                {'img':'fan39.jpg',
                 'width':'539',
                 'height':'557',
                 'intro':'作品名：缇娜的胖次，赞！<br>作者名：三色猫'
                },
                {'img':'fan40.jpg',
                 'width':'700',
                 'height':'711',
                 'intro':'作品名：我辣么萌！票呢！<br>作者名：绫纱岚'
                },
                {'img':'fan41.jpg',
                 'width':'700',
                 'height':'917',
                 'intro':'作品名：意外？<br>作者名：礼葬'
               },
                {'img':'fan16.jpg',
                 'width':'580',
                 'height':'823',
                 'intro':'作品名：猫耳瑟钰萌萌哒<br>作者名：walding'
                },          
                {'img':'fan17.jpg',
                 'width':'1000',
                 'height':'705',
                 'intro':'作品名：LEE<br>作者名：YO0'
                },
                {'img':'fan18.jpg',
                 'width':'1417',
                 'height':'2252',
                 'intro':'作品名：小米同人<br>作者名：春太阳青'
               }, 
                {'img':'fan20.jpg',
                 'width':'1000',
                 'height':'622',
                 'intro':'作品名：瑟钰 & 尤莉光甲<br>作者名：慢散君丶'
               },
                {'img':'fan1.jpg',
                 'width':'750',
                 'height':'528',
                 'intro':'作品名：世赫不懂怜香惜玉<br>作者名：六叶草phb'
                },
                {'img':'fan2.jpg',
                 'width':'1180',
                 'height':'1407',
                 'intro':'作品名：米斯丁<br>作者名：狼仔648'
                },
                {'img':'fan3.jpg',
                 'width':'1000',
                 'height':'707',
                 'intro':'作品名：黑羊小队全家福<br>作者名：DM丶CG'
                },
                {'img':'fan4.jpg',
                 'width':'800',
                 'height':'811',
                 'intro':'作品名：封印者们与C酱<br>作者名：刃湮骨'
                },
                {'img':'fan5.jpg',
                 'width':'2250',
                 'height':'3000',
                 'intro':'作品名：尤莉<br>作者名：慢散君丶'
                },
                {'img':'fan6.jpg',
                 'width':'580',
                 'height':'773',
                 'intro':'作品名：李世赫<br>作者名：慢散君丶'
                },
                {'img':'fan7.jpg',
                 'width':'580',
                 'height':'773',
                 'intro':'作品名：李瑟钰<br>作者名：慢散君丶'
                },
                
                {'img':'fan9.jpg',
                 'width':'580',
                 'height':'820',
                 'intro':'作品名：魔鬼身材尤莉<br>作者名：Nanoo33'
                },
                {'img':'fan10.jpg',
                 'width':'1000',
                 'height':'707',
                 'intro':'作品名：次元世界的C酱<br>作者名：『逆廻』十六夜'
               },  
            ],
            'imgWidth':227,
            'introHeight':60,
            'outerOffset':5,
            'innerOffset':5,
            'onUnitClickFun':function(i){
                preview(i);
            }
        };
        $(".imageList").barryFall(options);

        // 预加载大图
        var imgList = [],_path = options.picPath;
        $.each(options.unitData,function(i,data){
            imgList.push(data.img);
        });
        $.loadImg({
            'imgList':imgList,
            'url':_path,
            'callFinish':function(errList){ }
        });
    });    
});